"""
DO NOT EDIT - Auto-generated file
Generated by talon-pack v3.0.0

This file provides:
- Package version checking via parrot_tester_version() action
- Automatic dependency validation on startup
"""
import json
from pathlib import Path
from talon import Module, actions, app

mod = Module()

_cached_version = None

def _get_version() -> tuple[int, int, int]:
    """
    Loads version from manifest.json. Cached after first successful load.
    To reload: restart Talon or save this file
    """
    global _cached_version
    if _cached_version is not None:
        return _cached_version

    try:
        with open(Path(__file__).parent / 'manifest.json', 'r', encoding='utf-8') as f:
            version = tuple(map(int, json.load(f)['version'].split('.')))
            _cached_version = version
            return version
    except Exception as e:
        print(f"ERROR: talon-parrot-tester failed to load version from manifest.json: {e}")
        return (0, 0, 0)

@mod.action_class
class Actions:
    def parrot_tester_version() -> tuple[int, int, int]:
        """
        Returns the package version as (major, minor, patch).

        Usage: actions.user.parrot_tester_version() >= (1, 2, 0)
        """
        return _get_version()

def validate_dependencies():
    """
    Checks dependencies from manifest.json and calls {namespace}_version()
    for each to verify installed versions meet requirements on Talon startup.

    Prints warnings to Talon log when dependencies are missing or outdated,
    including installation/update instructions. Can be disabled by setting
    'validateDependencies': false in manifest.json.
    """
    try:
        manifest_path = Path(__file__).parent / 'manifest.json'
        with open(manifest_path, 'r') as f:
            data = json.load(f)

        if not data.get('validateDependencies', True):
            return

        deps = data.get('dependencies', {})
        errors = []

        for dep, info in deps.items():
            version_action_name = f"{info.get('namespace')}_version"
            github_url = info.get('github', '')
            version_str = info.get('min_version') or info.get('version')
            try:
                version_action = actions
                for part in version_action_name.split('.'):
                    version_action = getattr(version_action, part)
                installed = version_action()

                if not isinstance(installed, tuple):
                    installed = tuple(int(x) for x in str(installed).split('.'))

                required = tuple(int(x) for x in version_str.split('.'))
                if installed < required:
                    installed_str = '.'.join(map(str, installed))
                    errors.append(f"  Update {dep} to {version_str}+ (currently {installed_str})")
                    if github_url:
                        errors.append(f"    Navigate to the {dep} directory and run: git pull")
                        errors.append(f"    {github_url}")
                    errors.append("")
            except Exception as e:
                errors.append(f"  Cannot verify {dep} {version_str}+ (missing or invalid {version_action_name} action)")
                if github_url:
                    errors.append(f"    Install/update from: {github_url}")
                errors.append(f"    {e}")
                errors.append("")

        if errors:
            print(f"============================================================")
            print(f"{data.get('name')}: dependency requirements not met\n")
            for error in errors:
                print(error)
            print("  WARNING: Review code from unfamiliar sources before installing")
            print("  Note: You may need to restart Talon after updating")
            print("  To disable these warnings:")
            print(f"    Set 'validateDependencies': false in {manifest_path}")
            print(f"============================================================")
    except:
        pass

app.register("ready", validate_dependencies)
