"""
DO NOT EDIT - Auto-generated file
Generated by talon-manifest-generator v2.0.0

This file provides:
- Package version checking via parrot_tester_version() action
- Automatic dependency validation on startup
"""
import json
import os
from talon import Module, actions, app

mod = Module()

@mod.action_class
class Actions:
    def parrot_tester_version() -> tuple[int, int, int]:
        """
        Returns the package version as (major, minor, patch).

        Usage: actions.user.parrot_tester_version() >= (1, 2, 0)
        """
        manifest_path = os.path.join(os.path.dirname(__file__), 'manifest.json')
        with open(manifest_path, 'r', encoding='utf-8') as f:
            version_str = json.load(f)['version']
        return tuple(map(int, version_str.split('.')))

def validate_dependencies():
    """
    Checks dependencies from manifest.json and calls {namespace}_version()
    for each to verify installed versions meet requirements on Talon startup.

    Prints warnings to Talon log when dependencies are missing or outdated,
    including installation/update instructions. Can be disabled by setting
    'validateDependencies': false in manifest.json.
    """
    try:
        with open(os.path.join(os.path.dirname(__file__), 'manifest.json'), 'r') as f:
            data = json.load(f)

        if not data.get('validateDependencies', True):
            return

        deps = data.get('dependencies', {})
        errors = []

        for dep, info in deps.items():
            version_action = f"{info['namespace']}_version"
            github_url = info.get('github', '')
            try:
                action_ref = actions
                for part in version_action.split('.'):
                    action_ref = getattr(action_ref, part)
                installed = action_ref()
                required = tuple(int(x) for x in info['version'].split('.'))
                if installed < required:
                    installed_str = '.'.join(map(str, installed))
                    errors.append(f"  Update {dep} to {info['version']}+ (currently {installed_str})")
                    if github_url:
                        errors.append(f"    Navigate to the {dep} directory and run: git pull")
                        errors.append(f"    {github_url}")
            except AttributeError:
                errors.append(f"  Cannot verify {dep} {info['version']}+ (missing or invalid {version_action} action)")
                if github_url:
                    errors.append(f"    Install/update from: {github_url}")
            except Exception as e:
                errors.append(f"  {dep}: {e}")

        if errors:
            print(f"\n{data.get('name')}: dependency not met")
            for error in errors:
                print(error)
            print("  WARNING: Review code from unfamiliar sources before installing")
            print(f"  To disable these warnings, set 'validateDependencies': false in {data.get('name')}/manifest.json")
            print()
    except:
        pass

app.register("ready", validate_dependencies)
